version: "3.9"
services:
  backend:
    build: ./Backend
    ports:
      - "4001:4001"
    env_file:
      - ./Backend/.env 
  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    env_file:
      - ./Frontend/.env  
    stdin_open: true
    tty: true
    depends_on:
      - backend
