version: "3.9"
services:
  mongodb:
    image: "mongo"
    env_file:
      - ./env/mongo.env
  backend:
    build: ./Backend
    ports:
      - "4001:4001"
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
